apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: internal-client 
  namespace: apowine
  labels:
    role: client
    app: internal-client
    type: cli
spec:
  replicas: 1
  selector:
    matchLabels:
      app: internal-client
  template:
    metadata:
      name: apowine-internal-client
      labels:
        role: client
        app: internal-client
        type: cli
    spec:
      containers:
          - name: internal-client
            image: aporeto/apowine-clientcurl:latest
            env:
            - name: URI
              value: "demo.apowine.svc.cluster.local/internal"

