apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  creationTimestamp: null
  labels:
    app: aporeto-enforcer
  name: aporeto-enforcer
  namespace: kube-system
spec:
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: aporeto-enforcer
    spec:
      containers:
      - args:
        - -c
        - sleep 10; exec /enforcerd
        command:
        - /bin/sh
        env:
        - name: ENFORCERD_API
          valueFrom:
            configMapKeyRef:
              key: aporeto.cid_url
              name: aporeto-cm
        - name: ENFORCERD_LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              key: enforcerd.log_level
              name: aporeto-cm
        - name: ENFORCERD_LOG_FORMAT
          valueFrom:
            configMapKeyRef:
              key: enforcerd.log_format
              name: aporeto-cm
        - name: ENFORCERD_LOG_LEVEL_REMOTE
          valueFrom:
            configMapKeyRef:
              key: enforcerd.log_level
              name: aporeto-cm
        - name: ENFORCERD_API_CACERT
          valueFrom:
            configMapKeyRef:
              key: enforcerd.cacert
              name: aporeto-cm
        - name: ENFORCERD_LOG_TO_CONSOLE
          valueFrom:
            configMapKeyRef:
              key: enforcerd.log_to_console
              name: aporeto-cm
        image: aporeto/enforcerd:v1.296.1
        imagePullPolicy: Always
        name: enforcerd
        resources: {}
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /var/run
          name: dockersock
        - mountPath: /aporetoproc
          name: prochost
        - mountPath: /var/lib/aporeto
          name: shared-data
        - mountPath: /var/lib/registration
          name: certs
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      hostPID: true
      initContainers:
      - args:
        - register
        command:
        - /enforcerd
        env:
        - name: ENFORCERD_LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              key: enforcerd.log_level
              name: aporeto-cm
        - name: ENFORCERD_LOG_FORMAT
          valueFrom:
            configMapKeyRef:
              key: enforcerd.log_format
              name: aporeto-cm
        - name: ENFORCERD_SQUALL_NAMESPACE
          valueFrom:
            configMapKeyRef:
              key: enforcerd.namespace
              name: aporeto-cm
        - name: ENFORCERD_REGISTRATION_CERT
          valueFrom:
            configMapKeyRef:
              key: enforcerd.registration_cert
              name: aporeto-cm
        - name: ENFORCERD_API_CACERT
          valueFrom:
            configMapKeyRef:
              key: enforcerd.cacert
              name: aporeto-cm
        - name: ENFORCERD_FORCE
          valueFrom:
            configMapKeyRef:
              key: enforcerd.force_register
              name: aporeto-cm
        - name: ENFORCERD_API
          valueFrom:
            configMapKeyRef:
              key: aporeto.cid_url
              name: aporeto-cm
        - name: ENFORCERD_REGISTRATION_CERT_KEY
          valueFrom:
            configMapKeyRef:
              key: enforcerd.registration_cert_key
              name: aporeto-cm
        - name: ENFORCERD_LOG_TO_CONSOLE
          valueFrom:
            configMapKeyRef:
              key: enforcerd.log_to_console
              name: aporeto-cm
        - name: ENFORCERD_TAG
          valueFrom:
            configMapKeyRef:
              key: enforcerd.tag
              name: aporeto-cm
        image: aporeto/enforcerd:v1.296.1
        imagePullPolicy: Always
        name: registerer
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/aporeto
          name: shared-data
        - mountPath: /var/lib/registration
          name: certs
      volumes:
      - emptyDir: {}
        name: shared-data
      - hostPath:
          path: /proc
        name: prochost
      - hostPath:
          path: /var/run
        name: dockersock
      - name: certs
        secret:
          secretName: aporeto-secrets
  updateStrategy:
    type: RollingUpdate
status:
  currentNumberScheduled: 0
  desiredNumberScheduled: 0
  numberMisscheduled: 0
  numberReady: 0
